services:
  postgres:
    image: postgres:16
    container_name: coffee_postgres
    environment:
      POSTGRES_DB: coffee_db
      POSTGRES_USER: coffee_user
      POSTGRES_PASSWORD: coffee_pass
    ports:
      - "5432:5432"
    volumes:
      - coffee_pg_data:/var/lib/postgresql/data

volumes:
  coffee_pg_data:
